# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corporation 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.

apiVersion: management.apiconnect.ibm.com/v1beta1
kind: ManagementCluster
metadata:
  name: management
  labels: {
    app.kubernetes.io/instance: "management",
    app.kubernetes.io/managed-by: "ibm-apiconnect",
    app.kubernetes.io/name: "management"
  }
spec:
  version: 10.0.1.0
  imagePullSecrets:
  - ibm-entitlement-key
  imageRegistry: cp.icr.io/cp/apic
  profile: n1xc4.m16
  portal:
    admin:
      secretName: portal-admin-client
  analytics:
    client:
      secretName: analytics-client-client
    ingestion:
      secretName: analytics-ingestion-client
  gateway:
    client:
      secretName: gateway-client-client
  cloudManagerEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts: 
    - name: admin.$HOSTNAME
      secretName: cm-endpoint
  apiManagerEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts: 
    - name: manager.$HOSTNAME
      secretName: apim-endpoint
  platformAPIEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts: 
    - name: api.$HOSTNAME
      secretName: api-endpoint
  consumerAPIEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts: 
    - name: consumer.$HOSTNAME
      secretName: consumer-endpoint
  databaseVolumeClaimTemplate:
    storageClassName: gp2
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  license:
    accept: true
    use: nonproduction
